version: '2'

services:
  backend-1:
    image: datastax/dse-server:6.8.7
    container_name: backend-1
    networks:
      - backend
    ports:
      - 9044:9042
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - SEEDS=backend-1
      - CLUSTER_NAME=backend
      - DC=dc1
      - RACK=rack1
      - DS_LICENSE=accept
  backend-2:
    image: datastax/dse-server:6.8.7
    container_name: backend-2
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - backend-1
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - SEEDS=backend-1
      - CLUSTER_NAME=backend
      - DC=dc1
      - RACK=rack1
      - DS_LICENSE=accept
  backend-3:
    image: datastax/dse-server:6.8.7
    container_name: backend-3
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - backend-2
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - SEEDS=backend-1
      - CLUSTER_NAME=backend
      - DC=dc1
      - DS_LICENSE=accept
  stargate:
    image: stargateio/stargate-dse-68:v1.0.0
    container_name: stargate
    depends_on: 
      - backend-1
    networks:
      - backend
    ports:
      - 9045:9042
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8084:8084
    mem_limit: 2G
    environment:
      - JAVA_OPTS="-Xmx2G"
      - CLUSTER_NAME=backend
      - CLUSTER_VERSION=6.8
      - DSE=1
      - SEED=backend-1
      - RACK_NAME=rack1
      - DATACENTER_NAME=dc1
      - ENABLE_AUTH=true
networks:
  backend:
