version: '2'

services:
  backend-1:
    image: cassandra:3.11.8
    container_name: backend-1
    networks:
      - backend
    ports:
      - 9044:9042
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=backend-1
      - CASSANDRA_CLUSTER_NAME=backend
  backend-2:
    image: cassandra:3.11.8
    container_name: backend-2
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - backend-1
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=backend-1
      - CASSANDRA_CLUSTER_NAME=backend
  backend-3:
    image: cassandra:3.11.8
    container_name: backend-3
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - backend-2
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=backend-1
      - CASSANDRA_CLUSTER_NAME=backend
  stargate:
    image: stargateio/stargate-3_11:v1.0.0
    container_name: stargate
    depends_on: 
      - backend-1
    networks:
      - backend
    ports:
      - 9045:9042
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8084:8084
    mem_limit: 2G
    environment:
      - JAVA_OPTS="-Xmx2G"
      - CLUSTER_NAME=backend
      - CLUSTER_VERSION=3.11
      - SEED=backend-1
      - SIMPLE_SNITCH=true
      - ENABLE_AUTH=true
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on:
      - backend-1
      - stargate
    networks:
      - backend
    ports:
      - 9090:9090
    mem_limit: 2G
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on: 
      - backend-1
      - stargate
    networks:
      - backend
    ports:
      - 3000:3000
networks:
  backend:
